export const mainObj = {
	spirits: {
		id: 0,
		name: "spirits",
		items: [
			"absinthe",
			"gin",
			"vodka",
			"white rum",
			"dark rum",
			"bourbon",
			"rye whiskey",
			"scotch",
			"cognac",
			"tequila",
			"mezcal",
			"cognac",
			"tequila",
			"mezcal",
		],
		color: "navy",
	},
	liqueurs: {
		id: 1,
		name: "liqueurs",
		items: [
			"aperol",
			"campari",
			"cointreau",
			"coffee liqueur",
			"creme de cassis",
			"creme de violette",
			"green chartreuse",
			"maraschino liqueur",
			"st. germain",
			"yellow chartreuse",
		],
		color: "coral",
	},
	vermouth: {
		id: 2,
		name: "vermouth",
		items: ["dry vermouth", "sweet vermouth"],
		color: "purple",
	},
	amari: {
		id: 3,
		name: "amari",
		items: ["amaro nonino", "amaro ramazzotti", "amaro montenegro"],
		color: "brown",
	},
	juices: {
		id: 4,
		name: "juices",
		items: [
			"cranberry juice",
			"grapefruit juice",
			"lemon juice",
			"lime juice",
			"orange juice",
			"pineapple juice",
		],
		color: "green",
	},
	syrups: {
		id: 5,
		name: "syrups",
		items: ["agave syrup", "orgeat", "simple syrup"],
		color: "orange",
	},
	bubbles: {
		id: 6,
		name: "bubbles",
		items: ["prosecco", "soda water", "coke", "tonic"],
		color: "magenta",
	},
	bitters: {
		id: 7,
		name: "bitters",
		items: [
			"angostura bitters",
			"chocolate bitters",
			"spicy bitters",
			"orange bitters",
			"peychaud's bitters",
		],
		color: "tan",
	},
	garnishes: {
		id: 8,
		name: "garnishes",
		items: ["orange peel", "lemon peel", "cherry garnish"],
		color: "blue",
	},
	miscellaneous: {
		id: 9,
		name: "miscellaneous",
		items: ["egg", "egg white"],
		color: "teal",
	},
};
